services:
  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    depends_on: 
      - backend
    networks:
      - app-network

  backend:
    build: ./backend/
    container_name: backend
    volumes:
      - db:/app/prisma
      - avatars:/app/public/avatars
    restart: always
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - DEFAULT_AVATAR
      - HTTPS_CERT
      - HTTPS_KEY
      - JWT_EXPIRES_IN
    env_file:
      - ./backend/.env
    networks:
      - app-network

  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/certs:/etc/nginx/certs
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db:
  avatars: